### ISSUE TITLE
Doesn't work with node v6.12.0

### ISSUE THREAD

**Issue by oliverlorenz** [Cabalbl4/pseudonimizr#1]
```
Worker errored: TypeError: Object.values is not a function
    at Branch.walk (/home/olorenz/documents/code/figo/pseudonimizr/wordTreeBuilder.js:44:35)
    at WordTreeBuilder.propose (/home/olorenz/documents/code/figo/pseudonimizr/wordTreeBuilder.js:89:34)
    at BiasedSequenceRandomizer._biasedRandomize (/home/olorenz/documents/code/figo/pseudonimizr/randomizers.js:58:38)
    at BiasedSequenceRandomizer.randomize (/home/olorenz/documents/code/figo/pseudonimizr/randomizers.js:129:40)
    at Object.$.each (/home/olorenz/documents/code/figo/pseudonimizr/anonPlugin/html/index.js:57:61)
    at initialize.exports.each (/home/olorenz/documents/code/figo/pseudonimizr/node_modules/cheerio/lib/api/traversing.js:300:24)
    at HTMLParser.parse (/home/olorenz/documents/code/figo/pseudonimizr/anonPlugin/html/index.js:52:16)
    at Interface.lineReader.on (evalmachine.<anonymous>:31:22)
    at emitNone (events.js:91:20)
    at Interface.emit (events.js:185:7)
```

But its working with node v7.10.1 :smile:

**Comment by Cabalbl4** [comment]
Fixed
